export const STATUS_WAITING_FOR_APPROVE = "waiting_for_approve"
export const STATUS_APPROVED = "approved"
export const STATUS_ASSIGNED = "assigned"
export const STATUS_WAITING_FOR_MERGE = "waiting_for_merge"
export const STATUS_MERGED = "merged"
export const STATUS_CLOSED = "closed"
