export const RIGHTS_CR_CREATE = 'cr::create'
export const RIGHTS_CR_EDIT = 'cr::edit'
export const RIGHTS_CR_DELETE = 'cr::delete'
export const RIGHTS_CR_APPROVE = 'cr::approve'
export const RIGHTS_CR_ASSIGN = 'cr::assign'